version: '2'

services:

  rabbitmq:
    image: rabbitmq:3.6.10-management-alpine
    mem_limit: 512m
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq:rw

  camel:
    build:
      context: .
      dockerfile: Dockerfile-camel
    mem_limit: 256m
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -Xmx128m
      DB_URL: 10.13.170.251:1521:orcl
      DB_USERNAME: consignetflexprod
      DB_PASSWORD: consignetflexprod
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      - rabbitmq

  worker:
      build:
        context: .
        dockerfile: Dockerfile-worker
      mem_limit: 32m
      depends_on:
        - rabbitmq

volumes:
  rabbitmq-data:
    driver: local