FROM golang:1.8

ADD go/worker.go /go/src/worker/worker.go
ADD go/oci8.pc /usr/lib/pkgconfig/oci8.pc

RUN wget https://github.com/rue-vmom/docker-go-with-oracle-client/raw/master/instantclient-basic-linux.x64-11.2.0.4.0.zip
RUN wget https://github.com/rue-vmom/docker-go-with-oracle-client/raw/master/instantclient-sdk-linux.x64-11.2.0.4.0.zip

RUN apt-get update && apt-get install -y --no-install-recommends \
		unzip \
        libaio1 \
        && rm -rf /var/lib/apt/lists/*

RUN unzip instantclient-basic-linux.x64-*.zip -d / \
    && unzip instantclient-sdk-linux.x64-*.zip -d / \
    && ln -s /instantclient_11_2/libclntsh.so.11.1 /instantclient_11_2/libclntsh.so

ENV LD_LIBRARY_PATH /instantclient_11_2

RUN go get -d -v github.com/streadway/amqp
RUN go get -d -v gopkg.in/rana/ora.v4

RUN go install worker

ENTRYPOINT ["/go/bin/worker"]