version: '2'

services:

  rabbitmq:
    image: rabbitmq:3.6.10-management-alpine
    mem_limit: 512m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-net
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq:rw

  camel:
    build:
      context: .
    mem_limit: 256m
    ports:
      - "8080:8080"
    networks:
      - rabbitmq-net
    environment:
      JAVA_OPTS: -Xmx128m
      DB_URL: localhost:1521:orcl
      DB_USERNAME: guest
      DB_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      INBOUND_MAX: 50000

volumes:
  rabbitmq-data:
    driver: local

networks:
  rabbitmq-net:
    driver: bridge