spring:
  application:
    name: sample-camel
  datasource:
      url: jdbc:oracle:thin:@${DB_URL:localhost:1521:orcl}
      username: ${DB_USERNAME:guest}
      password: ${DB_PASSWORD:guest}
      driver-class-name: oracle.jdbc.driver.OracleDriver
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: ${PORT:8080}

info:
  component: ${spring.application.name}

management:
  security:
    enabled: false

camel:
  springboot:
    name: ${spring.application.name}

app:
  inbound-delay: ${INBOUND_DELAY:15000}
  inbound-max: ${INBOUND_MAX:10000}
  sql:
    calculo-margem: select * from calculo_margem where status = 0
    calculo-margem-consume: update calculo_margem set status = 1 where id = :#id
  amqp:
    calculo-margem: ${AMQP_QUEUE_NAME:calculo-margem}